import assert from 'node:assert/strict';
import fs from 'node:fs';
const source = fs.readFileSync(new URL('../src/popupQueue.js', import.meta.url), 'utf8');
const {PopupQueue} = await import(`data:text/javascript,${encodeURIComponent(source)}`);
let time = 0;
const queue = new PopupQueue(() => time);
const calls = [];
const request = (key, priority, blocked = false) => queue.request(key, priority, () => calls.push(key), blocked);
assert.equal(request('notification', 80), true);
assert.equal(request('mount', 30), false);
assert.equal(request('hud', 60), false);
assert.equal(request('mount', 30), false);
assert.equal(queue.pending.size, 2);
queue.next()();
assert.deepEqual(calls, ['hud']);
queue.next()();
assert.deepEqual(calls, ['hud', 'mount']);
assert.equal(request('bluetooth', 30), true);
assert.equal(request('vpn', 30), false);
assert.equal(request('notification', 80), true);
assert.equal(request('notification', 80), true);
queue.clear();
assert.equal(request('mount', 30, true), false);
time = 16000;
assert.equal(queue.next(), null);
console.log('PASS: priority, same-feature updates, bounded queue, equal-priority ordering, blocked events, expiry');
